### ISSUE TITLE
SOLVED

### ISSUE THREAD

**Issue by ShareWoodZ** [worldwidesorrow/Just-Another-Evac-Chopper-Mod#3]
dessapier action menu ("Set Evac-Chopper") if not plot pole naerby
video: https://youtu.be/jDtVaclbGRU

**Comment by worldwidesorrow** [comment]
Your self-actions are not clearing. Check to see if you have these lines:
https://github.com/worldwidesorrow/JAEM-v1.5/blob/master/dayz_code/compile/fn_selfActions.sqf#L729-L730

**Comment by ShareWoodZ** [comment]
https://pastebin.com/qzAVyfx2

**Comment by worldwidesorrow** [comment]
You are missing these two lines:
https://github.com/worldwidesorrow/JAEM-v1.5/blob/master/dayz_code/compile/fn_selfActions.sqf#L1103-L1104

**Comment by ShareWoodZ** [comment]
ohhh im blind))))
